import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
 await page.locator('#practice-start').click();await page.locator('#training-start').click();await page.locator('[data-lesson="cut-gentle"]').click();await page.locator('#training-library [data-hand="right"]').click();
 await page.locator('[data-execute]').click();
 await page.locator('#menu-toggle').click();await page.locator('[data-view="cue"]').click();
 const state=()=>page.evaluate(()=>{const s=window.__noir.scene;return {angle:s.angle,tip:s.tip,pos:s.camera.position.toArray(),target:s.controls.target.toArray(),distance:s.camera.position.distanceTo(s.controls.target)};});
 const base=await state();
 await page.locator('[data-camera="low"]').click();
 assert.ok((await state()).pos[1]<.3,'Low view reaches ball height');
 assert.equal((await state()).angle,base.angle);
 await page.screenshot({path:'artifacts/cue-camera-eye-level.png'});
 await page.locator('[data-camera="reset"]').click();
 await page.locator('[data-camera="contact"]').click();
 await page.waitForFunction(()=>window.__noir.scene.scene.getObjectByName('live-contact-aid').visible);
 const contact=()=>page.evaluate(()=>window.__noir.scene.scene.getObjectByName('live-contact-point').position.toArray());
 const firstContact=await contact();
 await page.evaluate(()=>{window.__noir.scene.angle+=.01;});
 await page.waitForTimeout(100);assert.notDeepEqual(await contact(),firstContact,'Contact follows current aim');
 await page.screenshot({path:'artifacts/live-contact-aid.png'});
 await page.evaluate(()=>{window.__noir.scene.angle=Math.PI;});await page.waitForTimeout(100);
 assert.equal(await page.evaluate(()=>window.__noir.scene.scene.getObjectByName('live-contact-point').visible),false,'No invented point on a missed ball');
 await page.evaluate(angle=>{window.__noir.scene.angle=angle;},base.angle);
 await page.locator('[data-camera="contact"]').click();
 await page.waitForFunction(()=>!window.__noir.scene.scene.getObjectByName('live-contact-aid').visible);
 await page.locator('[data-camera="reset"]').click();
 await page.locator('[data-camera="high"]').click();
 assert.ok(await page.evaluate(()=>window.__noir.scene.controls.getPolarAngle()<.08),'High view looks almost straight down');
 assert.equal((await state()).angle,base.angle);
 await page.screenshot({path:'artifacts/cue-camera-high.png'});
 await page.locator('[data-camera="reset"]').click();
 await page.screenshot({path:'artifacts/cue-camera-default.png'});
 await page.locator('[data-camera="near"]').click();assert.ok((await state()).distance<base.distance);
 await page.locator('[data-camera="far"]').click();
 await page.locator('[data-camera="left"]').click();assert.notDeepEqual((await state()).pos,base.pos);
 await page.locator('[data-camera="up"]').click();assert.ok((await state()).pos[1]>base.pos[1]);
 assert.equal((await state()).angle,base.angle);assert.deepEqual((await state()).tip,base.tip);
 await page.locator('[data-camera="reset"]').click();
 assert.ok(Math.abs((await state()).distance-base.distance)<.001);
 const canvas=await page.locator('#scene canvas').boundingBox(),x=canvas.x+canvas.width*.5,y=canvas.y+canvas.height*.4;
 await page.mouse.move(x,y);await page.mouse.wheel(0,-250);await page.waitForTimeout(200);
 assert.ok((await state()).distance<base.distance,'Wheel zooms in cue view');
 await page.mouse.down({button:'right'});await page.mouse.move(x+120,y+25,{steps:10});await page.mouse.up({button:'right'});await page.waitForTimeout(400);
 assert.equal((await state()).angle,base.angle,'Orbit does not aim');
 await page.evaluate(()=>{const c=window.__noir.scene.controls;c.enableDamping=false;c.update();c.enableDamping=true;});
 const rotated=(await state()).pos;await page.setViewportSize({width:1200,height:820});await page.waitForTimeout(300);
 assert.ok((await state()).pos.every((v,i)=>Math.abs(v-rotated[i])<.03),'Resize preserves camera');
 await page.locator('[data-camera="reset"]').click();
 await page.locator('#menu-toggle').click();await page.locator('[data-view="top"]').click();
 assert.equal(await page.locator('.cue-camera-tools').isVisible(),false);
 assert.equal(await page.evaluate(()=>window.__noir.scene.controls.enableZoom),false);
 await page.setViewportSize({width:390,height:844});
 await page.locator('#menu-toggle').click();await page.locator('[data-view="cue"]').click();
 await page.locator('#phone-camera').click();
 await page.locator('[data-camera="near"]').click();await page.locator('[data-camera="right"]').click();
 await page.screenshot({path:'artifacts/cue-camera-mobile.png'});
 assert.equal(await page.locator('[data-camera="reset"]').isVisible(),true);
 await page.locator('[data-camera="reset"]').click();
 const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:2});
 await page.locator('#phone-camera').click();
 const beforeTouch=await state(),rect=await page.locator('#scene canvas').boundingBox();
 const cx=rect.x+rect.width*.5,cy=rect.y+rect.height*.35;
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-30,y:cy,id:1},{x:cx+30,y:cy,id:2}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-55,y:cy+12,id:1},{x:cx+55,y:cy+12,id:2}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(300);
 assert.equal((await state()).angle,beforeTouch.angle,'Two-finger gestures must never aim');
 assert.ok((await state()).distance<beforeTouch.distance,'Pinch zoom works on touch devices');
 await page.locator('#phone-camera').click();
 await page.locator('[data-camera="reset"]').click();
 for(let i=0;i<20;i++)await page.locator('[data-camera="near"]').click();
 assert.ok((await state()).distance>=1.59,'Close-up has a safe minimum distance');
 assert.ok((await state()).pos[1]>.25,'Camera remains above the table');
 assert.deepEqual(errors,[]);console.log('PASS cue camera: framing, zoom, orbit, height, reset, unchanged aim, resize and mobile controls');
}finally{await browser.close();}
